package com.restapi.siscondominio.financiero.persistence.repositories;
import com.restapi.siscondominio.financiero.persistence.documents.evidenciaIncidenciasNoSolucionadasDocuments;
import org.springframework.data.mongodb.repository.MongoRepository;
public interface FinEvidenciaIncidenciaNoSolucionadasRepositoryMD extends MongoRepository<evidenciaIncidenciasNoSolucionadasDocuments,String> {
}
